"""add author fields to blog_posts

Revision ID: 1842a34f73fa
Revises: 4729f043217b
Create Date: 2026-03-04 11:32:57.280181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1842a34f73fa'
down_revision = '4729f043217b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('author_photo_url', sa.String(length=600), nullable=True))
        batch_op.add_column(sa.Column('author_contact', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('author_contact')
        batch_op.drop_column('author_photo_url')
        batch_op.drop_column('author_name')

    # ### end Alembic commands ###
