"""add blog_authors table, refactor blog_post author fields

Revision ID: 1bab787daad7
Revises: 1842a34f73fa
Create Date: 2026-03-04 12:13:01.891881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1bab787daad7'
down_revision = '1842a34f73fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=600), nullable=True),
    sa.Column('photo_key', sa.String(length=300), nullable=True),
    sa.Column('contact', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_key', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('blog_author_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_blog_posts_blog_author_id'), ['blog_author_id'], unique=False)
        batch_op.create_foreign_key(None, 'blog_authors', ['blog_author_id'], ['id'])
        batch_op.drop_column('author_photo_url')
        batch_op.drop_column('author_contact')
        batch_op.drop_column('author_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_name', mysql.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('author_contact', mysql.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('author_photo_url', mysql.VARCHAR(length=600), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_blog_posts_blog_author_id'))
        batch_op.drop_column('blog_author_id')
        batch_op.drop_column('cover_image_key')

    op.drop_table('blog_authors')
    # ### end Alembic commands ###
