"""add blog categories and post category relation

Revision ID: 4729f043217b
Revises: 7dff0d24f709
Create Date: 2026-03-04 10:55:10.064766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4729f043217b'
down_revision = '7dff0d24f709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('blog_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_categories_slug'), ['slug'], unique=True)

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_blog_posts_category_id'), ['category_id'], unique=False)
        batch_op.create_foreign_key(None, 'blog_categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_blog_posts_category_id'))
        batch_op.drop_column('category_id')

    with op.batch_alter_table('blog_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_categories_slug'))

    op.drop_table('blog_categories')
    # ### end Alembic commands ###
